### ISSUE TITLE
Update drupal console to latest RC release

### ISSUE THREAD

**Issue by grayside** [phase2/docker-build#5]
We would like to support the latest 1.x RC release of drupal Console, as despite not having a stable release it is required in a lot of cases. This issue was originally for porting a solution, but that solution was found not to work.

**Comment by febbraro** [comment]
Is this still relevant? I thought I saw some chatter around things not still working as expected.

**Comment by grayside** [comment]
The general assumption with Drupal Console is that it should be a local install, not global, which trips some people up. However, the local install when done via docker/nfs AND with a deep filesystem such as Pattern Lab Starter's node_modules causes a massive performance fail.

**Comment by grayside** [comment]
Updated the issue since this is no longer a portage task.

**Comment by febbraro** [comment]
We have removed Drupal Console from the image all together. This is now a project dependency.
